// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: admin.sql

package gensqlc

import (
	"context"

	"github.com/google/uuid"
)

const upsertAdmin = `-- name: UpsertAdmin :exec
INSERT INTO admins (user_id, login, hashed_password)
VALUES ($1, $2, $3)
ON CONFLICT (user_id)
DO UPDATE SET login = $2, hashed_password = $3
`

type UpsertAdminParams struct {
	UserID         uuid.UUID
	Login          string
	HashedPassword string
}

func (q *Queries) UpsertAdmin(ctx context.Context, arg UpsertAdminParams) error {
	_, err := q.db.Exec(ctx, upsertAdmin, arg.UserID, arg.Login, arg.HashedPassword)
	return err
}
