// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package gensqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, full_name)
VALUES ($1, $2)
ON CONFLICT (id)
DO UPDATE SET full_name = $2
`

type UpsertUserParams struct {
	ID       uuid.UUID
	FullName string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser, arg.ID, arg.FullName)
	return err
}
