// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: customers.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomersServiceClient is the client API for CustomersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomersServiceClient interface {
	GetCustomers(ctx context.Context, in *GetCustomersRequest, opts ...grpc.CallOption) (*GetCustomersResponse, error)
	SetCustomerDiscountById(ctx context.Context, in *SetCustomerDiscountByIdRequest, opts ...grpc.CallOption) (*SetCustomerDiscountByIdResponse, error)
	ExportCustomersToExcel(ctx context.Context, in *ExportCustomersToExcelRequest, opts ...grpc.CallOption) (*ExportCustomersToExcelResponse, error)
	AddCustomer(ctx context.Context, in *AddCustomerRequest, opts ...grpc.CallOption) (*AddCustomerResponse, error)
}

type customersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomersServiceClient(cc grpc.ClientConnInterface) CustomersServiceClient {
	return &customersServiceClient{cc}
}

func (c *customersServiceClient) GetCustomers(ctx context.Context, in *GetCustomersRequest, opts ...grpc.CallOption) (*GetCustomersResponse, error) {
	out := new(GetCustomersResponse)
	err := c.cc.Invoke(ctx, "/customers.CustomersService/GetCustomers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersServiceClient) SetCustomerDiscountById(ctx context.Context, in *SetCustomerDiscountByIdRequest, opts ...grpc.CallOption) (*SetCustomerDiscountByIdResponse, error) {
	out := new(SetCustomerDiscountByIdResponse)
	err := c.cc.Invoke(ctx, "/customers.CustomersService/SetCustomerDiscountById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersServiceClient) ExportCustomersToExcel(ctx context.Context, in *ExportCustomersToExcelRequest, opts ...grpc.CallOption) (*ExportCustomersToExcelResponse, error) {
	out := new(ExportCustomersToExcelResponse)
	err := c.cc.Invoke(ctx, "/customers.CustomersService/ExportCustomersToExcel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersServiceClient) AddCustomer(ctx context.Context, in *AddCustomerRequest, opts ...grpc.CallOption) (*AddCustomerResponse, error) {
	out := new(AddCustomerResponse)
	err := c.cc.Invoke(ctx, "/customers.CustomersService/AddCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomersServiceServer is the server API for CustomersService service.
// All implementations must embed UnimplementedCustomersServiceServer
// for forward compatibility
type CustomersServiceServer interface {
	GetCustomers(context.Context, *GetCustomersRequest) (*GetCustomersResponse, error)
	SetCustomerDiscountById(context.Context, *SetCustomerDiscountByIdRequest) (*SetCustomerDiscountByIdResponse, error)
	ExportCustomersToExcel(context.Context, *ExportCustomersToExcelRequest) (*ExportCustomersToExcelResponse, error)
	AddCustomer(context.Context, *AddCustomerRequest) (*AddCustomerResponse, error)
	mustEmbedUnimplementedCustomersServiceServer()
}

// UnimplementedCustomersServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCustomersServiceServer struct {
}

func (UnimplementedCustomersServiceServer) GetCustomers(context.Context, *GetCustomersRequest) (*GetCustomersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomers not implemented")
}
func (UnimplementedCustomersServiceServer) SetCustomerDiscountById(context.Context, *SetCustomerDiscountByIdRequest) (*SetCustomerDiscountByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCustomerDiscountById not implemented")
}
func (UnimplementedCustomersServiceServer) ExportCustomersToExcel(context.Context, *ExportCustomersToExcelRequest) (*ExportCustomersToExcelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportCustomersToExcel not implemented")
}
func (UnimplementedCustomersServiceServer) AddCustomer(context.Context, *AddCustomerRequest) (*AddCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCustomer not implemented")
}
func (UnimplementedCustomersServiceServer) mustEmbedUnimplementedCustomersServiceServer() {}

// UnsafeCustomersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomersServiceServer will
// result in compilation errors.
type UnsafeCustomersServiceServer interface {
	mustEmbedUnimplementedCustomersServiceServer()
}

func RegisterCustomersServiceServer(s grpc.ServiceRegistrar, srv CustomersServiceServer) {
	s.RegisterService(&CustomersService_ServiceDesc, srv)
}

func _CustomersService_GetCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServiceServer).GetCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customers.CustomersService/GetCustomers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServiceServer).GetCustomers(ctx, req.(*GetCustomersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomersService_SetCustomerDiscountById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCustomerDiscountByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServiceServer).SetCustomerDiscountById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customers.CustomersService/SetCustomerDiscountById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServiceServer).SetCustomerDiscountById(ctx, req.(*SetCustomerDiscountByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomersService_ExportCustomersToExcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportCustomersToExcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServiceServer).ExportCustomersToExcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customers.CustomersService/ExportCustomersToExcel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServiceServer).ExportCustomersToExcel(ctx, req.(*ExportCustomersToExcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomersService_AddCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServiceServer).AddCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customers.CustomersService/AddCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServiceServer).AddCustomer(ctx, req.(*AddCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomersService_ServiceDesc is the grpc.ServiceDesc for CustomersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customers.CustomersService",
	HandlerType: (*CustomersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomers",
			Handler:    _CustomersService_GetCustomers_Handler,
		},
		{
			MethodName: "SetCustomerDiscountById",
			Handler:    _CustomersService_SetCustomerDiscountById_Handler,
		},
		{
			MethodName: "ExportCustomersToExcel",
			Handler:    _CustomersService_ExportCustomersToExcel_Handler,
		},
		{
			MethodName: "AddCustomer",
			Handler:    _CustomersService_AddCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customers.proto",
}
